name: Cripto-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          hash_length=$(python -c "import random; import string; print(len(''.join(random.choice(string.ascii_letters + string.digits) for i in range(6))) == 6)")
          if [ "$hash_length" = true ]; then
            echo "Success: Hash length is correct."
          else
            echo "Failure: Hash length is incorrect."
            exit 1
          fi
