name: Cripto-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          hash_output=$(python main.py)
          echo "Random hash output: $hash_output"
          
          # Checking if the output contains "Success"
          if [[ "$hash_output" != *"Success"* ]]; then
            echo "Hash length validation failed"
            exit 1
          else
            echo "Hash length validation succeeded"
          fi
