name: Crypto-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          python_hash = generate_random_hash(k)
          echo "Generated hash: $python_hash"
          if [ ${#python_hash} -eq 6 ]; then
            echo "Hash length is 6 characters"
          else
            echo "Hash length is not 6 characters"
            exit 1
          fi

