name: Crypto-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          k=6
          python_hash=$(python -c "import random, string; print(''.join(random.choices(string.ascii_letters + string.digits, k=$k)))")
          echo "Generated hash: $python_hash"
          if [ ${#python_hash} -ne $k ]; then
            echo "Hash length is not $k characters"
            exit 1
          else
            echo "Hash length is $k characters"
          fi

