name: Python-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          python_code=$(cat main.py)
          python_result=$(python -c "$python_code")
          if [ "$python_result" == "6" ]; then
            echo "Success: k is 6"
          else
            echo "Failure: k is not 6"
            exit 1
          fi


